array_width = 100
binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
chain_width = 100
comment_width = 80
control_brace_style = "AlwaysSameLine"
edition = "2024"
empty_item_single_line = true
enum_discrim_align_threshold = 0
fn_params_layout = "Compressed"
fn_single_line = true
format_strings = true
imports_granularity = "Crate"
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
max_width = 120
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
style_edition = "2024"
tab_spaces = 2
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
